<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $countries = array(
            array("code" => "USA", "name" => "United States of America", "phonecode" => 1),
            array("code" => "CA", "name" => "Canada", "phonecode" => 1),
            array("code" => "AF", "name" => "Afghanistan", "phonecode" => 93),
            array("code" => "AL", "name" => "Albania", "phonecode" => 355),
            array("code" => "DZ", "name" => "Algeria", "phonecode" => 213),
            array("code" => "AS", "name" => "American Samoa", "phonecode" => 1684),
            array("code" => "AD", "name" => "Andorra", "phonecode" => 376),
            array("code" => "AO", "name" => "Angola", "phonecode" => 244),
            array("code" => "AI", "name" => "Anguilla", "phonecode" => 1264),
            array("code" => "AQ", "name" => "Antarctica", "phonecode" => 0),
            array("code" => "AG", "name" => "Antigua And Barbuda", "phonecode" => 1268),
            array("code" => "AR", "name" => "Argentina", "phonecode" => 54),
            array("code" => "AM", "name" => "Armenia", "phonecode" => 374),
            array("code" => "AW", "name" => "Aruba", "phonecode" => 297),
            array("code" => "AU", "name" => "Australia", "phonecode" => 61),
            array("code" => "AT", "name" => "Austria", "phonecode" => 43),
            array("code" => "AZ", "name" => "Azerbaijan", "phonecode" => 994),
            array("code" => "BS", "name" => "Bahamas The", "phonecode" => 1242),
            array("code" => "BH", "name" => "Bahrain", "phonecode" => 973),
            array("code" => "BD", "name" => "Bangladesh", "phonecode" => 880),
            array("code" => "BB", "name" => "Barbados", "phonecode" => 1246),
            array("code" => "BY", "name" => "Belarus", "phonecode" => 375),
            array("code" => "BE", "name" => "Belgium", "phonecode" => 32),
            array("code" => "BZ", "name" => "Belize", "phonecode" => 501),
            array("code" => "BJ", "name" => "Benin", "phonecode" => 229),
            array("code" => "BM", "name" => "Bermuda", "phonecode" => 1441),
            array("code" => "BT", "name" => "Bhutan", "phonecode" => 975),
            array("code" => "BO", "name" => "Bolivia", "phonecode" => 591),
            array("code" => "BA", "name" => "Bosnia and Herzegovina", "phonecode" => 387),
            array("code" => "BW", "name" => "Botswana", "phonecode" => 267),
            array("code" => "BV", "name" => "Bouvet Island", "phonecode" => 0),
            array("code" => "BR", "name" => "Brazil", "phonecode" => 55),
            array("code" => "IO", "name" => "British Indian Ocean Territory", "phonecode" => 246),
            array("code" => "BN", "name" => "Brunei", "phonecode" => 673),
            array("code" => "BG", "name" => "Bulgaria", "phonecode" => 359),
            array("code" => "BF", "name" => "Burkina Faso", "phonecode" => 226),
            array("code" => "BI", "name" => "Burundi", "phonecode" => 257),
            array("code" => "KH", "name" => "Cambodia", "phonecode" => 855),
            array("code" => "CM", "name" => "Cameroon", "phonecode" => 237),
            array("code" => "CV", "name" => "Cape Verde", "phonecode" => 238),
            array("code" => "KY", "name" => "Cayman Islands", "phonecode" => 1345),
            array("code" => "CF", "name" => "Central African Republic", "phonecode" => 236),
            array("code" => "TD", "name" => "Chad", "phonecode" => 235),
            array("code" => "CL", "name" => "Chile", "phonecode" => 56),
            array("code" => "CN", "name" => "China", "phonecode" => 86),
            array("code" => "CX", "name" => "Christmas Island", "phonecode" => 61),
            array("code" => "CC", "name" => "Cocos (Keeling) Islands", "phonecode" => 672),
            array("code" => "CO", "name" => "Colombia", "phonecode" => 57),
            array("code" => "KM", "name" => "Comoros", "phonecode" => 269),
            array("code" => "CG", "name" => "Congo", "phonecode" => 242),
            array("code" => "CD", "name" => "Congo The Democratic Republic Of The", "phonecode" => 242),
            array("code" => "CK", "name" => "Cook Islands", "phonecode" => 682),
            array("code" => "CR", "name" => "Costa Rica", "phonecode" => 506),
            array("code" => "CI", "name" => "Cote D Ivoire (Ivory Coast)", "phonecode" => 225),
            array("code" => "HR", "name" => "Croatia (Hrvatska)", "phonecode" => 385),
            array("code" => "CU", "name" => "Cuba", "phonecode" => 53),
            array("code" => "CY", "name" => "Cyprus", "phonecode" => 357),
            array("code" => "CZ", "name" => "Czech Republic", "phonecode" => 420),
            array("code" => "DK", "name" => "Denmark", "phonecode" => 45),
            array("code" => "DJ", "name" => "Djibouti", "phonecode" => 253),
            array("code" => "DM", "name" => "Dominica", "phonecode" => 1767),
            array("code" => "DO", "name" => "Dominican Republic", "phonecode" => 1809),
            array("code" => "TP", "name" => "East Timor", "phonecode" => 670),
            array("code" => "EC", "name" => "Ecuador", "phonecode" => 593),
            array("code" => "EG", "name" => "Egypt", "phonecode" => 20),
            array("code" => "SV", "name" => "El Salvador", "phonecode" => 503),
            array("code" => "GQ", "name" => "Equatorial Guinea", "phonecode" => 240),
            array("code" => "ER", "name" => "Eritrea", "phonecode" => 291),
            array("code" => "EE", "name" => "Estonia", "phonecode" => 372),
            array("code" => "ET", "name" => "Ethiopia", "phonecode" => 251),
            array("code" => "XA", "name" => "External Territories of Australia", "phonecode" => 61),
            array("code" => "FK", "name" => "Falkland Islands", "phonecode" => 500),
            array("code" => "FO", "name" => "Faroe Islands", "phonecode" => 298),
            array("code" => "FJ", "name" => "Fiji Islands", "phonecode" => 679),
            array("code" => "FI", "name" => "Finland", "phonecode" => 358),
            array("code" => "FR", "name" => "France", "phonecode" => 33),
            array("code" => "GF", "name" => "French Guiana", "phonecode" => 594),
            array("code" => "PF", "name" => "French Polynesia", "phonecode" => 689),
            array("code" => "TF", "name" => "French Southern Territories", "phonecode" => 0),
            array("code" => "GA", "name" => "Gabon", "phonecode" => 241),
            array("code" => "GM", "name" => "Gambia The", "phonecode" => 220),
            array("code" => "GE", "name" => "Georgia", "phonecode" => 995),
            array("code" => "DE", "name" => "Germany", "phonecode" => 49),
            array("code" => "GH", "name" => "Ghana", "phonecode" => 233),
            array("code" => "GI", "name" => "Gibraltar", "phonecode" => 350),
            array("code" => "GR", "name" => "Greece", "phonecode" => 30),
            array("code" => "GL", "name" => "Greenland", "phonecode" => 299),
            array("code" => "GD", "name" => "Grenada", "phonecode" => 1473),
            array("code" => "GP", "name" => "Guadeloupe", "phonecode" => 590),
            array("code" => "GU", "name" => "Guam", "phonecode" => 1671),
            array("code" => "GT", "name" => "Guatemala", "phonecode" => 502),
            array("code" => "XU", "name" => "Guernsey and Alderney", "phonecode" => 44),
            array("code" => "GN", "name" => "Guinea", "phonecode" => 224),
            array("code" => "GW", "name" => "Guinea-Bissau", "phonecode" => 245),
            array("code" => "GY", "name" => "Guyana", "phonecode" => 592),
            array("code" => "HT", "name" => "Haiti", "phonecode" => 509),
            array("code" => "HM", "name" => "Heard and McDonald Islands", "phonecode" => 0),
            array("code" => "HN", "name" => "Honduras", "phonecode" => 504),
            array("code" => "HK", "name" => "Hong Kong S.A.R.", "phonecode" => 852),
            array("code" => "HU", "name" => "Hungary", "phonecode" => 36),
            array("code" => "IS", "name" => "Iceland", "phonecode" => 354),
            array("code" => "IN", "name" => "India", "phonecode" => 91),
            array("code" => "ID", "name" => "Indonesia", "phonecode" => 62),
            array("code" => "IR", "name" => "Iran", "phonecode" => 98),
            array("code" => "IQ", "name" => "Iraq", "phonecode" => 964),
            array("code" => "IE", "name" => "Ireland", "phonecode" => 353),
            array("code" => "IL", "name" => "Israel", "phonecode" => 972),
            array("code" => "IT", "name" => "Italy", "phonecode" => 39),
            array("code" => "JM", "name" => "Jamaica", "phonecode" => 1876),
            array("code" => "JP", "name" => "Japan", "phonecode" => 81),
            array("code" => "XJ", "name" => "Jersey", "phonecode" => 44),
            array("code" => "JO", "name" => "Jordan", "phonecode" => 962),
            array("code" => "KZ", "name" => "Kazakhstan", "phonecode" => 7),
            array("code" => "KE", "name" => "Kenya", "phonecode" => 254),
            array("code" => "KI", "name" => "Kiribati", "phonecode" => 686),
            array("code" => "KP", "name" => "Korea North", "phonecode" => 850),
            array("code" => "KR", "name" => "Korea South", "phonecode" => 82),
            array("code" => "KW", "name" => "Kuwait", "phonecode" => 965),
            array("code" => "KG", "name" => "Kyrgyzstan", "phonecode" => 996),
            array("code" => "LA", "name" => "Laos", "phonecode" => 856),
            array("code" => "LV", "name" => "Latvia", "phonecode" => 371),
            array("code" => "LB", "name" => "Lebanon", "phonecode" => 961),
            array("code" => "LS", "name" => "Lesotho", "phonecode" => 266),
            array("code" => "LR", "name" => "Liberia", "phonecode" => 231),
            array("code" => "LY", "name" => "Libya", "phonecode" => 218),
            array("code" => "LI", "name" => "Liechtenstein", "phonecode" => 423),
            array("code" => "LT", "name" => "Lithuania", "phonecode" => 370),
            array("code" => "LU", "name" => "Luxembourg", "phonecode" => 352),
            array("code" => "MO", "name" => "Macau S.A.R.", "phonecode" => 853),
            array("code" => "MK", "name" => "Macedonia", "phonecode" => 389),
            array("code" => "MG", "name" => "Madagascar", "phonecode" => 261),
            array("code" => "MW", "name" => "Malawi", "phonecode" => 265),
            array("code" => "MY", "name" => "Malaysia", "phonecode" => 60),
            array("code" => "MV", "name" => "Maldives", "phonecode" => 960),
            array("code" => "ML", "name" => "Mali", "phonecode" => 223),
            array("code" => "MT", "name" => "Malta", "phonecode" => 356),
            array("code" => "XM", "name" => "Man (Isle of)", "phonecode" => 44),
            array("code" => "MH", "name" => "Marshall Islands", "phonecode" => 692),
            array("code" => "MQ", "name" => "Martinique", "phonecode" => 596),
            array("code" => "MR", "name" => "Mauritania", "phonecode" => 222),
            array("code" => "MU", "name" => "Mauritius", "phonecode" => 230),
            array("code" => "YT", "name" => "Mayotte", "phonecode" => 269),
            array("code" => "MX", "name" => "Mexico", "phonecode" => 52),
            array("code" => "FM", "name" => "Micronesia", "phonecode" => 691),
            array("code" => "MD", "name" => "Moldova", "phonecode" => 373),
            array("code" => "MC", "name" => "Monaco", "phonecode" => 377),
            array("code" => "MN", "name" => "Mongolia", "phonecode" => 976),
            array("code" => "MS", "name" => "Montserrat", "phonecode" => 1664),
            array("code" => "MA", "name" => "Morocco", "phonecode" => 212),
            array("code" => "MZ", "name" => "Mozambique", "phonecode" => 258),
            array("code" => "MM", "name" => "Myanmar", "phonecode" => 95),
            array("code" => "NA", "name" => "Namibia", "phonecode" => 264),
            array("code" => "NR", "name" => "Nauru", "phonecode" => 674),
            array("code" => "NP", "name" => "Nepal", "phonecode" => 977),
            array("code" => "AN", "name" => "Netherlands Antilles", "phonecode" => 599),
            array("code" => "NL", "name" => "Netherlands The", "phonecode" => 31),
            array("code" => "NC", "name" => "New Caledonia", "phonecode" => 687),
            array("code" => "NZ", "name" => "New Zealand", "phonecode" => 64),
            array("code" => "NI", "name" => "Nicaragua", "phonecode" => 505),
            array("code" => "NE", "name" => "Niger", "phonecode" => 227),
            array("code" => "NG", "name" => "Nigeria", "phonecode" => 234),
            array("code" => "NU", "name" => "Niue", "phonecode" => 683),
            array("code" => "NF", "name" => "Norfolk Island", "phonecode" => 672),
            array("code" => "MP", "name" => "Northern Mariana Islands", "phonecode" => 1670),
            array("code" => "NO", "name" => "Norway", "phonecode" => 47),
            array("code" => "OM", "name" => "Oman", "phonecode" => 968),
            array("code" => "PK", "name" => "Pakistan", "phonecode" => 92),
            array("code" => "PW", "name" => "Palau", "phonecode" => 680),
            array("code" => "PS", "name" => "Palestinian Territory Occupied", "phonecode" => 970),
            array("code" => "PA", "name" => "Panama", "phonecode" => 507),
            array("code" => "PG", "name" => "Papua new Guinea", "phonecode" => 675),
            array("code" => "PY", "name" => "Paraguay", "phonecode" => 595),
            array("code" => "PE", "name" => "Peru", "phonecode" => 51),
            array("code" => "PH", "name" => "Philippines", "phonecode" => 63),
            array("code" => "PN", "name" => "Pitcairn Island", "phonecode" => 0),
            array("code" => "PL", "name" => "Poland", "phonecode" => 48),
            array("code" => "PT", "name" => "Portugal", "phonecode" => 351),
            array("code" => "PR", "name" => "Puerto Rico", "phonecode" => 1787),
            array("code" => "QA", "name" => "Qatar", "phonecode" => 974),
            array("code" => "RE", "name" => "Reunion", "phonecode" => 262),
            array("code" => "RO", "name" => "Romania", "phonecode" => 40),
            array("code" => "RU", "name" => "Russia", "phonecode" => 70),
            array("code" => "RW", "name" => "Rwanda", "phonecode" => 250),
            array("code" => "SH", "name" => "Saint Helena", "phonecode" => 290),
            array("code" => "KN", "name" => "Saint Kitts And Nevis", "phonecode" => 1869),
            array("code" => "LC", "name" => "Saint Lucia", "phonecode" => 1758),
            array("code" => "PM", "name" => "Saint Pierre and Miquelon", "phonecode" => 508),
            array("code" => "VC", "name" => "Saint Vincent And The Grenadines", "phonecode" => 1784),
            array("code" => "WS", "name" => "Samoa", "phonecode" => 684),
            array("code" => "SM", "name" => "San Marino", "phonecode" => 378),
            array("code" => "ST", "name" => "Sao Tome and Principe", "phonecode" => 239),
            array("code" => "SA", "name" => "Saudi Arabia", "phonecode" => 966),
            array("code" => "SN", "name" => "Senegal", "phonecode" => 221),
            array("code" => "RS", "name" => "Serbia", "phonecode" => 381),
            array("code" => "SC", "name" => "Seychelles", "phonecode" => 248),
            array("code" => "SL", "name" => "Sierra Leone", "phonecode" => 232),
            array("code" => "SG", "name" => "Singapore", "phonecode" => 65),
            array("code" => "SK", "name" => "Slovakia", "phonecode" => 421),
            array("code" => "SI", "name" => "Slovenia", "phonecode" => 386),
            array("code" => "XG", "name" => "Smaller Territories of the UK", "phonecode" => 44),
            array("code" => "SB", "name" => "Solomon Islands", "phonecode" => 677),
            array("code" => "SO", "name" => "Somalia", "phonecode" => 252),
            array("code" => "ZA", "name" => "South Africa", "phonecode" => 27),
            array("code" => "GS", "name" => "South Georgia", "phonecode" => 0),
            array("code" => "SS", "name" => "South Sudan", "phonecode" => 211),
            array("code" => "ES", "name" => "Spain", "phonecode" => 34),
            array("code" => "LK", "name" => "Sri Lanka", "phonecode" => 94),
            array("code" => "SD", "name" => "Sudan", "phonecode" => 249),
            array("code" => "SR", "name" => "Suriname", "phonecode" => 597),
            array("code" => "SJ", "name" => "Svalbard And Jan Mayen Islands", "phonecode" => 47),
            array("code" => "SZ", "name" => "Swaziland", "phonecode" => 268),
            array("code" => "SE", "name" => "Sweden", "phonecode" => 46),
            array("code" => "CH", "name" => "Switzerland", "phonecode" => 41),
            array("code" => "SY", "name" => "Syria", "phonecode" => 963),
            array("code" => "TW", "name" => "Taiwan", "phonecode" => 886),
            array("code" => "TJ", "name" => "Tajikistan", "phonecode" => 992),
            array("code" => "TZ", "name" => "Tanzania", "phonecode" => 255),
            array("code" => "TH", "name" => "Thailand", "phonecode" => 66),
            array("code" => "TG", "name" => "Togo", "phonecode" => 228),
            array("code" => "TK", "name" => "Tokelau", "phonecode" => 690),
            array("code" => "TO", "name" => "Tonga", "phonecode" => 676),
            array("code" => "TT", "name" => "Trinidad And Tobago", "phonecode" => 1868),
            array("code" => "TN", "name" => "Tunisia", "phonecode" => 216),
            array("code" => "TR", "name" => "Turkey", "phonecode" => 90),
            array("code" => "TM", "name" => "Turkmenistan", "phonecode" => 7370),
            array("code" => "TC", "name" => "Turks And Caicos Islands", "phonecode" => 1649),
            array("code" => "TV", "name" => "Tuvalu", "phonecode" => 688),
            array("code" => "UG", "name" => "Uganda", "phonecode" => 256),
            array("code" => "UA", "name" => "Ukraine", "phonecode" => 380),
            array("code" => "AE", "name" => "United Arab Emirates", "phonecode" => 971),
            array("code" => "GB", "name" => "United Kingdom", "phonecode" => 44),
            array("code" => "UY", "name" => "Uruguay", "phonecode" => 598),
            array("code" => "UZ", "name" => "Uzbekistan", "phonecode" => 998),
            array("code" => "VU", "name" => "Vanuatu", "phonecode" => 678),
            array("code" => "VA", "name" => "Vatican City State (Holy See)", "phonecode" => 39),
            array("code" => "VE", "name" => "Venezuela", "phonecode" => 58),
            array("code" => "VN", "name" => "Vietnam", "phonecode" => 84),
            array("code" => "VG", "name" => "Virgin Islands (British)", "phonecode" => 1284),
            array("code" => "VI", "name" => "Virgin Islands (US)", "phonecode" => 1340),
            array("code" => "WF", "name" => "Wallis And Futuna Islands", "phonecode" => 681),
            array("code" => "EH", "name" => "Western Sahara", "phonecode" => 212),
            array("code" => "YE", "name" => "Yemen", "phonecode" => 967),
            array("code" => "YU", "name" => "Yugoslavia", "phonecode" => 38),
            array("code" => "ZM", "name" => "Zambia", "phonecode" => 260),
            array("code" => "ZW", "name" => "Zimbabwe", "phonecode" => 263)
        );
        DB::table('countries')->insert($countries);
        //Country::create($countries);
    }
}
